name: share_handler_ios
description: An implementation for the iOS platform of the Flutter share_handler plugin.
repository: https://github.com/AboutShout/share_handler/tree/main/share_handler_ios
version: 0.0.9

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
#  share_handler_platform_interface: ^0.0.5
  share_handler_platform_interface:
    git:
      url: https://github.com/vietinfo/share_handler.git
      path: share_handler_platform_interface

#  share_handler_platform_interface:
#    path: ../share_handler_platform_interface

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ShareHandlerIosPlatform
        podspec: ios/ShareHandlerIos.podspec
