name: share_handler_web
description: An implementation for the Web platform of the Flutter share_handler plugin.
repository: https://github.com/AboutShout/share_handler/tree/main/share_handler_platform_web
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  share_handler_platform_interface: ^0.0.1

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ShareHandlerWebPlatform
        fileName: share_handler_web.dart
